<?php return array(
    'root' => array(
        'name' => 'artefactual/accesstomemory',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'artefactual/accesstomemory' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'elasticsearch/elasticsearch' => array(
            'pretty_version' => 'v5.4.0',
            'version' => '5.4.0.0',
            'reference' => 'd3c5b55ad94f5053ca76c48585b4cde2cdc6bc59',
            'type' => 'library',
            'install_path' => __DIR__ . '/../elasticsearch/elasticsearch',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.19.0',
            'version' => '4.19.0.0',
            'reference' => 'b287d2a16aceffbf6e0295559b39662612b77fcf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/ringphp' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => '5e2a174052995663dd68e6b5ad838afd47dd615b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/ringphp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/streams' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '47aaa48e27dae43d39fc1cea0ccf0d84ac1a2ba5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/streams',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jasig/phpcas' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'reference' => 'c129708154852656aabb13d8606cd5b12dbbabac',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jasig/phpcas',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/csv' => array(
            'pretty_version' => '9.8.0',
            'version' => '9.8.0.0',
            'reference' => '9d2e0265c5d90f5dd601bc65ff717e05cec19b47',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/csv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v2.11.0',
            'version' => '2.11.0.0',
            'reference' => '1a8460931ea36dc5c76838fec5734d55c88c6831',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ruflin/elastica' => array(
            'pretty_version' => '5.3.6',
            'version' => '5.3.6.0',
            'reference' => '1ed6f587a38d4d6455b688ffc9a9d370d4ae60e9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ruflin/elastica',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
